### ISSUE TITLE
Option to git clone via http(s)

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#10]
Right now `furyctl install` downloads packages via git clone that uses ssh. In some environments the ssh use is banned. It would be nice if `furyctl` had a flag that would enable the clone/download via http(s) instead

**Comment by angelbarrera92** [comment]
I can work on it if you don't mind ;)

**Comment by phisco** [comment]
I tried to implement this once but found some issues with go-getter not fully supporting git via https (not sure about it) and the fact that we are using subpaths of repositories and with https at the time it wasn’t super straight forward

**Comment by angelbarrera92** [comment]
Uhmmmm. I have a local working version cloning with https.

Take a look to: https://github.com/sighupio/furyctl/pull/new/feature/git-via-https

Let me know if i miss something!

**Comment by phisco** [comment]
Happy to be proven wrong! I was probably using the wrong url for https. I’ll try to run the proposed PR asap, but just by giving a look to the code changes I’d say it’s pretty straight forward and think I think it should be good 👏🏻
