### ISSUE TITLE
Furyctl v0.6 vendor doesn't fail when it can't write to disk

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#107]
Running `furyctl vendor -H` inside a folder that the current user can't write to, shows absolutely no error and normal output but the vendor folder is nowhere to be found.

**Comment by luigibarbato** [comment]
the issue not present in furyctl 0.8.0. weh furyctl can't write to the folder it prints the proper error:

`ERRO[0028] mkdir vendor: permission denied`
