### ISSUE TITLE
Introduce terraform state bucket creation in `furyctl create cluster`

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#138]
Furyctl Next has the capabilities and the needed information to create the S3 bucket where to store the terraform state if it does not exist. This could be performed together with the cluster creation.

Decided if we want Furyctl Next to handle this and implement it if it is so.

Related:
- https://github.com/sighupio/furyctl/issues/223

**Comment by omissis** [comment]
implemented by #448
