### ISSUE TITLE
[Furyctl Next] only use sudo if necessary

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#140]
Furyctl Next uses `sudo` to setup the openvpn connection, but without doing any prior checks.

It shall use `sudo` only when needed, for example, if the user is not `root`.

**Comment by Al-Pragliola** [comment]
As discussed on https://github.com/sighupio/furyctl/pull/131#discussion_r1061333838 , we should also add the command with or without sudo to kill the OpenVPN process after cluster deletion.
