### ISSUE TITLE
[Furyctl next QA] Test scenarios list

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/furyctl#196]
We need to test furyctl-ng with the following test scenarios:

- [ ] Create a simple cluster with a barebone distribution
- [ ] Create a cluster with an existing VPC/VPN
- [ ] Deploy distribution with the following permutations
   - [ ] Ingress
     - [ ] With provided SSL certificate
     - [ ] Using cert-manager with dns01 challenge
     - [ ] Using cert-manager with http01 challenge
     - [ ] Using an existing route53 zone for the public DNS
     - [ ] Creating a new route53 zone for the public DNS
  - [ ] Authentication
     - [ ] Using no authentication on ingresses
     - [ ] Using SSO on ingresses (with github sso integration)
     - [ ] Using basicAuth on ingresses

**Comment by g-iannelli** [comment]
Additional test cases:

- [ ] Installation of the KFD distribution on top an existing EKS cluster

**Comment by nutellinoit** [comment]
We already tested these scenarios in more than one event, I will close the issue
