### ISSUE TITLE
Execute validation before `furyctl.yaml` has been created

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#205]
When create a `furyctl.yaml` file executing `furyctl create config`, there is no validation against apiVersion.

E.g. 

As defined at [ekscluster-kfd-v1alpha2.json](https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/schemas/ekscluster-kfd-v1alpha2.json) the name of the cluster must have length beetween 1 and 19. 
I'm able to create the `furyctl.yaml` using the name `eks-barebone-engineering-dev` that is longer than 19 chars.

**Comment by ralgozino** [comment]
Steps to reproduce:
1. `furyctl create config --name eks-barebone-engineering-dev <other flags>`
2. furyctl creates a configuration file that then won't pass the validation because the cluster name is too long.
