### ISSUE TITLE
Tools download does not check for the user os architecture

### ISSUE THREAD

**Issue by Al-Pragliola** [sighupio/furyctl#206]
When downloading the required tools, amd64 is a fixed value in the OS arch. We should check and use the users' one instead.

**Comment by Al-Pragliola** [comment]
blocked because this breaks furyctl users with arm64 os arch, terraform 0.15.4 does not have an arm64 build

**Comment by ralgozino** [comment]
Relates:
- sighupio/product-management#39

**Comment by nutellinoit** [comment]
Closing as completed
