### ISSUE TITLE
Please specify which `awscli` version is required

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#219]
When download dependencies, please specify which `awscli` version is required.

In my case, I have already installed to a newer version and it's not compatible with the KFD requirements.

Please, provide an automatic and indipendent way to download `awscli` when download dependencies

**Comment by ralgozino** [comment]
The version check has been addressed in the linked PR, we should also document that the awscli is needed but not managed by furyctl

**Comment by nutellinoit** [comment]
the aws version check is in place, closing
