### ISSUE TITLE
Don't set default value for `.spec.kubernetes.vpcId`

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#220]
As by default the VPC is created in `infrastructure` phase, please don't set any default variable for `.spec.kubernetes.vpcId`

**Comment by ralgozino** [comment]
Should be addressed as part of sighupio/product-management#140

**Comment by ralgozino** [comment]
known issue, closing in favour of https://github.com/sighupio/product-management/issues/140
