### ISSUE TITLE
Missing aws module support

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#225]
In the `kfd.sighup.io/v1alpha2` there is no reference to [fury aws module](https://github.com/sighupio/fury-kubernetes-aws).

It's required to install `ebs-csi-driver`,`cluster-autoscaler` or `aws-loadbalancer-controller`.

**Comment by ralgozino** [comment]
The AWS module is included in the template used to create the kustomize project for the cluster:

https://github.com/sighupio/fury-distribution/blob/97732f9c4a0894e598627b317a2bc7ffd9326f90/templates/distribution/manifests/aws/kustomization.yaml.tpl

What were you looking for in particular?

**Comment by g-iannelli** [comment]
I'm looking for how to integrate the Terraform modules present on `fury aws module`

**Comment by ralgozino** [comment]
Evaluate what parameters could be exposed for the AWS module, and to enable / disable some parts.

For example, the IAM role could already exist and you may want to use it instead of creating one for default.
