### ISSUE TITLE
Missing the capability to create extra IAM role

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#226]
There is no way to add some new IAM roles that may be required when IRSA is in place or to fill the aws-auth configMap

**Comment by ralgozino** [comment]
I think this is covered already in the following section of the configuration file:

https://github.com/sighupio/fury-distribution/blob/97732f9c4a0894e598627b317a2bc7ffd9326f90/templates/config/ekscluster-kfd-v1alpha2.yaml.tpl#L137-L150

isn't it?

**Comment by g-iannelli** [comment]
No, I mean how to create a new IAM Roles, maybe with AssumeRoleWithWebIdentity and then use them

**Comment by nutellinoit** [comment]
Not in scope on furyctl, if you need additional IAM roles, furyctl is not the tool for that, an additional terraform project should be used
