### ISSUE TITLE
Remove .git dir triggered in furyctl init

### ISSUE THREAD

**Issue by nikever** [sighupio/furyctl#26]
Hello, 

there is a bug since we added the removing of the `.git` directories.
When  running `furyctl init` it tries to removes `.git` folder in `Furyfile.yml/.git`. Luckily it results in an error and nothing happens but given the fact that the Furyfile sits usually at the root level at the repository, this can be dangerous :D 

To reproduce:

```
furyctl init --version v1.5.0
INFO[0000] downloading: github.com/sighupio/fury-distribution/releases/download/v1.5.0/Furyfile.yml -> Furyfile.yml 
INFO[0001] removing Furyfile.yml/.git                   
ERRO[0001] unlinkat Furyfile.yml/.git: not a directory  
INFO[0001] unlinkat Furyfile.yml/.git: not a directory
```

**Comment by angelbarrera92** [comment]
What do you expect to have it solved? Ignore the `.git` only in the current directory?

**Comment by nikever** [comment]
I think it should avoid removing `.git` stuff when doing the `furyctl init`but only in `furyctl vendor`

**Comment by lzecca78** [comment]
@nikever  , @angelbarrera92  take a look to the referenced commit i did in the branch :)

**Comment by angelbarrera92** [comment]
Ok, understood! Is only on `init`, I didn't get at first attempt

**Comment by angelbarrera92** [comment]
Fixed:

Update it to 0.2.6 running: `brew upgrade furyctl`

Thanks @lzecca78 !
