### ISSUE TITLE
Resources no longer needed are not deleted

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#266]
Resources no longer needed are not deleted, for example if you switch from `spec.distribution.modules.auth.provider.type` from `sso` to `none`, `dex` and `pomerium` resources are still in place.

**Comment by nutellinoit** [comment]
This problem will be discussed in a next release, we don't have right now a way to reconcile this change

**Comment by nutellinoit** [comment]
This has already been addressed with migration feature
