### ISSUE TITLE
How configure kubectl timeout?

### ISSUE THREAD

**Issue by g-iannelli** [sighupio/furyctl#269]
```shell
ERRO error while deleting resources: error deleting resources: command timed out after 5m0s: /Users/giuseppe.iannelli/.furyctl/bin/kubectl/1.24.9/kubectl /Users/giuseppe.iannelli/.furyctl/bin/kubectl/1.24.9/kubectl delete --ignore-not-found=true -f /var/folders/k9/3lv0pm253td7mqnyhqfryprw0000gn/T/furyctl-dist-manifests-3780269848/out.yaml
```

How can I configure the kubectl timeout?

**Comment by ralgozino** [comment]
We already have planned this:
- #144 

If this is a different issue, please feel free to re-open it.

**Comment by g-iannelli** [comment]
It has nothing to do with ingress deletion. The timeout occurs during other deletions.

**Comment by ralgozino** [comment]
Maybe from the error we can figure it out, but, to avoid guessing or making bad assumptions, it would be better if you add more context to the issue, for example: what command did you run, if you had some particular configuration, what happened after the error, etc.

could you please add some more details?

thanks!

**Comment by omissis** [comment]
We will be adding a global timeout flag(eg: `--timeout=25m`) that will control timeouts depending on the case. to be evaluate with @g-iannelli
