### ISSUE TITLE
Reintroduce MinimalConf validation

### ISSUE THREAD

**Issue by omissis** [sighupio/furyctl#290]
I have temporarily removed minimal conf validation from `internal/distribution/download.go`'s `Downloader.DoDownload()` function. We need to reintroduce it after the vpn rework in #163 .

Original code:

```
if err := d.validate.Struct(minimalConf); err != nil {
	return DownloadResult{}, fmt.Errorf("invalid furyctl config: %w", err)
}
```

**Comment by Al-Pragliola** [comment]
keep in mind to work https://github.com/sighupio/furyctl/issues/175 after this.
