### ISSUE TITLE
Preflight checks

### ISSUE THREAD

**Issue by angelbarrera92** [sighupio/furyctl#30]
Furyctl should perform preflight checks on its dependencies and see if they are present.

We need to identify them and the furyctl should run checks if

- the needed tools are present (furyagent, terraform, etc..)
- the needed configuration is present (env vars, credentials, etc.)

if any of these dependencies is missing, furyctl should fail as fast as possible with a clear error message.

Example:

The `aws` bootstrap provisioner requires some environment variables to be present before running any `furyctl bootstrap {init,apply,destroy}` command. 

The main idea is to check them, then fail fast reporting the problem to the user as soon as possible (if any).

> edited by @ralgozino on September 6th 2022

**Comment by ralgozino** [comment]
closing this issue because it will be addressed in the next gen version of Furyctl

for internal purposes see: sighupio/product-management#40
