### ISSUE TITLE
.spec.region is not being used

### ISSUE THREAD

**Issue by ralgozino** [sighupio/furyctl#303]
Th EKSCluster schema has a `spec.region` field to specify the region where to create all the resources (cluster, VPN, VPC, etc.) that is not currently being used and the `AWS_DEFAULT_REGION` environment variable is being picked instead.

furyctl shall use the value specified in the configuration file instead of the default region environment variable.

Tasks:

- [ ] update infrastructure phase terraform templates
- [ ] update kubernetes phase terraform templates
- [ ] update distribution phase terraform templates
- [ ] update dependency check (don't check for AWS_DEFAULT_REGION presence)
- [ ] update the schema and make `.spec.region` mandatory if it's not that way

See #293 for terraform logs

**Comment by Al-Pragliola** [comment]
related issue #293

**Comment by omissis** [comment]
@ralgozino I think so, we probably just forgot to do so
