### ISSUE TITLE
Introduce vpn connect and disconnect commands

### ISSUE THREAD

**Issue by omissis** [sighupio/furyctl#312]
Please add two furyctl subcommands to make it simpler to connect and disconnect from the configured vpn:

`furyctl connect openvpn furyctl.yaml`
`furyctl disconnect openvpn furyctl.yaml`

**Comment by alessiodionisi** [comment]
The PR https://github.com/sighupio/furyctl/pull/329 introduces `furyctl connect openvpn` with foreground process
