### ISSUE TITLE
Furyctl(next) - Improve VPN handling

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/furyctl#365]
I'm opening this issue to address the problem we have around the management of the VPN users in the event of a private cluster.

Right now, the process involves the creation of a user with the same name of the user that is executing furyctl ( `whoami` command) . Also, in the event we lose the home folder (that is something that should not be a problem, se issue #356 ) we are revoking and regenerating the certificate, forcing the user to reconfigure the vpn.

My suggested approach is the following:

- We should create a generic user tied to the name of the cluster, using the `.medatada.name` field, and if the folder is no more present, we should only regenerate the ovpn file, and not revoke and recreate the certificate (a quick fix can be to change this behaviour https://github.com/sighupio/furyagent/blob/4d9a0f09a3db55a753101f83f456afad7bc0350a/pkg/component/openvpnclient.go#L193 to only regenerate ovpn file instead of failing)
- We should port the features of `furyagent` inside furyctl, and deprecate `furyagent` tool (yes, this is **BIG**)
- We should copy the secret used to generate ovpn certificates ( example `/Users/samuelechiocca/.furyctl/kubecon-ams-23/infrastructure/terraform/secrets/furyagent.yml` ) in the workdir where `furyctl.yaml` file is, this way we can create other arbitrary .ovpn certificates (like we do on all the clusters), OR we can leverage only `furyctl.yaml` file to get the needed infos

**Comment by omissis** [comment]
Hi, my two cents below:

- I would not go for using a single vpn certificate as a way to access the cluster, as it's probably not a good security practice and discourage accountability. I am not even sure it can be an accepted policy for tight-security environment. I believe we should instead go for enabling access for an explicit set of users. if the end user decides to go for a single, shared vpn certificate it should be their choice
- copying the secret (or any other file) to the work dir only moves the problem. we should try to make the process idempotent, and think about how we want to drive secrets sharing, possibly trying to minimize them. 
- the proposed solution of keeping the secret in the work dir does not play well with a collaborative environment, unless we want to require the certificate to be committed to the repository in order for other people to work on the project, so we should think about how this should work before committing to a solution
