### ISSUE TITLE
Missing information on openvpn requirements

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/furyctl#37]
https://docs.kubernetesfury.com/docs/cli-reference/furyctl/provisioners/aws-bootstrap/#requirements

Hi team, this is more a furyagent problem, but because `openvpn` executable is needed by furyagent and because furyctl uses furyagent under the hood,  we should document/add some infos on the boostrap process.

@lbottalico found this issue on the AWS boostrap

**Comment by nutellinoit** [comment]
Yes, we can work on that 👍🏻

**Comment by ralgozino** [comment]
We have a first approach to dependencies validation that will be introduced in #92 but we still need to update the dependencies definition file (`kfd.yaml`) with optional or required information.
