### ISSUE TITLE
Default ingress secret "ingress-nginx-global-tls-cert" not create when provider is set to secret

### ISSUE THREAD

**Issue by giusepperotella** [sighupio/furyctl#423]
When the provider is set to secret in the `furyctl.yaml` file, the secret used by default from ingress nginx `ingress-nginx-global-tls-cert` is not created.
Environment:
- kubernetes 1.24 on-prem;
- furyctl 0.25.1

Step to reproduce the problem:
- Install cluster using on-prem playbook.
- use furctl version 0.25.1 with scope "KFDDistribution"

Identified workaround:
add in the `templates/distribution/manifests/ingress/kustomization.yaml.tpl` , the following if:
```
{{ if eq .spec.distribution.modules.ingress.nginx.tls.provider "secret" }}
  - secrets/tls.yml
{{- end }} 
```

**Comment by nutellinoit** [comment]
This has already been fixed, closing
