### ISSUE TITLE
Allow ssh key along with Github username during bootstrapping

### ISSUE THREAD

**Issue by nandajavarma** [sighupio/furyctl#44]
Currently only GITHUB_USER is accepted in bootstrap.yml. Allow it to accept also SSH key like in the cluster.yml

**Comment by ralgozino** [comment]
In the new `furyctl.yaml` schema we have considered this option under the key `spec.infrastructure.vpn.ssh.{githubUsersName,publicKeys}`, this has not been implemented yet though.

**Comment by ralgozino** [comment]
This is what I'd do:

1. If we don't support specifying the SSH key for the VPN node, add that feature.
2. Announce that we'll deprecate the GitHub keys for the VPN nodes in the future, I'd even make furyctl stamp a warning if it finds it defined. Maybe we can add some statistics to see if it is being used or not?
3. Deprecate the GitHub option in a few releases

**Comment by ralgozino** [comment]
Related:
- https://github.com/sighupio/fury-eks-installer/pull/21
- https://github.com/sighupio/furyagent/pull/27
