### ISSUE TITLE
Support for ALB attachment to autoscaling groups created by furyctl

### ISSUE THREAD

**Issue by lnovara** [sighupio/furyctl#47]
While creating a cluster we stumbled upon an "issue" in furyctl which prevents us form attaching an ALB to an autoscaling groups created during the cluster provisioning.

Scenario: we created the ALB using Terraform on attached it to the cluster using the [`aws_lb_target_group_attachment`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment) resource. Everything works fine but at the next `furyctl cluster apply --dry-run` we get the following plan:

```
# module.fury.module.cluster.aws_autoscaling_group.workers[0] will be updated in-place
  ~ resource "aws_autoscaling_group" "workers" {
        id                        = "XXXXXX"
        name                      = "XXXXXX"
      ~ target_group_arns         = [
          - "XXXXXX",
        ]
        # (23 unchanged attributes hidden)
        # (8 unchanged blocks hidden)
    }
```

What is happening here is that furyctl tells us that it will remove the attachment we just created rendering the ALB unable to forward the traffic to the cluster.

While looking at the upstream Terraform module we saw that we can use the [`target_group_arns`](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L88) in the worker definition to prevent the attachment removal.

Can we expose such parameter as part of the `nodePools` field when dealing with EKS clusters?

Thank you.

**Comment by lnovara** [comment]
Any feedback about this?

I think this behavior can be quite dangerous as it may cause downtime in case the target group is detached from the nodes and the traffic stops flowing altogether.

**Comment by angelbarrera92** [comment]
Solved!
