### ISSUE TITLE
Add support for authentication through IAM roles

### ISSUE THREAD

**Issue by lnovara** [sighupio/furyctl#48]
We are experimenting with AWS account federation using IAM roles and we stumbled upon a furyctl limitation in that area: as of now, it is not possible to authenticate to a given AWS account using an IAM role while Terraform supports this use case just fine.

Would it be possible to include support for such feature?

As of now, we are working around this issue manually calling the assumRole API from AWS CLI and then exporting the resulting credentials as environment variables.

References:
 - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html
 - https://support.hashicorp.com/hc/en-us/articles/360041289933-Using-AWS-AssumeRole-with-the-AWS-Terraform-Provider

**Comment by nutellinoit** [comment]
Is this ok @alessiodionisi ?

**Comment by alessiodionisi** [comment]
This type of authentication can already be done by configuring a profile for the AWS CLI and the AWS_PROFILE env.

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html

**Comment by nutellinoit** [comment]
Ok, I will close this as complete then, thank you!
