### ISSUE TITLE
Custom AMI support

### ISSUE THREAD

**Issue by lnovara** [sighupio/furyctl#51]
In order to support GPU and ARM workload on EKS the user is required to use a specific AMI.

Currently, clusters created with `furyctl` cannot leverage such features as there is no way to specify the AMI used for a given node pool.

References:
- https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html#gpu-ami
- https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html#arm-ami

**Comment by angelbarrera92** [comment]
Solved!
