### ISSUE TITLE
Introduce EKS add-ons

### ISSUE THREAD

**Issue by lnovara** [sighupio/furyctl#69]
Upgrading an EKS cluster does not update core components that come with the cluster such as vpc-cni, coredns and kube-proxy. In the past, this required to pull the updated Kubernetes resources for such components and applying them to the cluster. Now, AWS introduced EKS add-ons to address this issue thus allowing the upgrade of such components in a straightforward way.

I think we should add this feature (available since EKS v1.18) to improve day-2 operations management.

Ref:
  - https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html

**Comment by lnovara** [comment]
Corresponding `fury-eks-installer` issue: sighupio/fury-eks-installer#32

**Comment by omissis** [comment]
removing from furyctl-v0.10.0 milestone as it is not blocking the release

**Comment by nutellinoit** [comment]
Closing as duplicated
